 <!doctype html>
<html>
<head>
    <?php require_once('head.php'); ?>
</head>
<body>
    <div id="page" class="clearfix">
        <?php $t = 7; require_once('header.php'); ?>
        <div id="container" class="clearfix"> 
            <div class="template clearfix">
                <div class="w_content clearfix"> 
                    <h2 class="title_art">UDTALELSER OM MALERARBEJDE</h2> 
                    <div class="form_ipinions"> 
                        <input class="txtInput" placeholder="Navn *" type="text">
                        <input class="txtInput" placeholder="E-mail *" type="text"> 
                        <textarea class="txtArea" placeholder="Indlæg *"></textarea>
                        <div class="w_btn clearfix">
                            <a href="#" class="btn_gem">Gem indlæg</a>
                            <span class="sp_note">Felter markeret * skal udfyldes</span>                            
                        </div>
                    </div>                    
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Sidsel og Louis</span></div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">13-08-2014 21:35:54</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Vi skulle have istandsat vores lejlighed som er en ældre ejendom og alle vægge havde struktur maling fra gammel tid som var næsten umulig at forvandle uden at rive alle vægge ned. Efter mange tilbud fra murer, kom jeg i kontakt med DLH som løste opgaven på fineste vis uden at vi skulle rive alle vægge ned. Dertil var der heller ingen tvivl ved første møde at både tilbud og kemi var god. David og Louise har vores varmeste anbefalinger og der er ingen tvivl om at næste gang vi eller vores venner skal have renoveret at vi vil bruge dem igen. DLH var meget fleksible og udførte alt til tiden. Rigtig god kommunikation og løsninger under hele processen.<br><br>Tak for denne gang og på gensyn<br><br>Mvh<br>Sidsel og Louis, Frederiksberg </td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Jette og Lars</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:Ukendt@ukendt.dk">Ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">13-08-2014 11:08:41</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Vi har fået istandsat et værelse i en ældre københavner-lejlighed. Entreprisen viste sig at blive meget besværlig, fordi væggene bestod af løst puds direkte på hønsenet. Det fine er, at det aldrig blev vores problem, at der var uforudsete benspænd undervejs i processen - der var aldrig tvivl om, at det meget rimelige tilbud, vi havde fået fra DLH, stod ved magt. Solidt og nydeligt udført håndværk til en pris, som bestemt er konkurrencedygtig - tak for denne gang og på gensyn!<br><br>Dbh.<br>Jette og Lars</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Philip</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">08-01-2014 15:36:14</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Jeg har for noget tid siden fået malet min lejlighed hos DLH, og kan kun varmt anbefale dem.<br><br>Arbejdet blev udført flot og til tiden.<br><br>Der er ingen tvivl om at jeg kommer til at bruge dem igen næste gang.<br><br>Mvh<br>Philip</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Svend E. Pedersen</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:svendp@post.tele.dk">svendp@post.tele.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">19-12-2013 13:01:34</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Som formand for andelsboligforeningen Holmebo skal jeg efter et omfattende malerarbejde udtrykke anerkendelse af kvalitet i arbejdet og behagelig service. God kontakt mellem kunde og medarbejdere.  Der er faldet mange positive bemærkninger fra vore medlemmer. Vi har nu malerfirmaet på vores faste håndværkerliste.</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Svend E. Pedersen</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:svendp@post.tele.dk">svendp@post.tele.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">19-12-2013 13:01:31</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Som formand for andelsboligforeningen Holmebo skal jeg efter et omfattende malerarbejde udtrykke anerkendelse af kvalitet i arbejdet og behagelig service. God kontakt mellem kunde og medarbejdere.  Der er faldet mange positive bemærkninger fra vore medlemmer. Vi har nu malerfirmaet på vores faste håndværkerliste.</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Rasmus Nylander</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">07-01-2013 10:57:01</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Vi har brugt Malerfirmaet DLH til flere projekter indendørs og udendørs. Det har været en stor fornøjelse, da finish, kvalitet og humøret altid er højt ved dem - og arbejdspladsen er pænt ryddet når arbejdet er overstået. Vi kan varmt anbefale Malerfirmaet DLH til andre private og virksomheder, som ønsker malerarbejdet udført korrekt og til tiden.<br> <br>Med venlig hilsen / Best regards<br> <br>Rasmus Nylander<br>Neptun Spa &amp; Pool</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Gitte og Thomas</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">07-01-2013 10:56:01</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Vi skulle have kalket et køkken og malet et badeværelse i en gammel ejendom i indre by. Vi valgte Malerfirmaet DLH, da de gav det billigste tilbud og desuden virkede både kompetente og behagelige. Da malerarbejdet blev påbegyndt, blev det klart at en større renovation af badeværelset var nødvendig. DLH satte os i kontakt med andre håndværkere, som gennemførte renovationen af badeværelset til fuld tilfredshed. Malerarbejdet blev koordineret med de øvrige håndværkere, og vi var meget tilfredse med det færdige resultat. DLH har under hele forløbet været meget fleksible og har lagt en ære i at levere et flot stykke arbejde. I et par tilfælde hvor aftaler blev ændret, har DLH været flinke til hver gang at give besked i god tid i forvejen. Vi tøver ikke med at give vores fulde anbefaling til Malerfirmaet DLH.<br><br>Gitte og Thomas fra København.</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Karin og Peter</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">07-01-2013 10:55:20</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">"Vi fik i sensommer 2012 istandsæt vores opgang, hvor der skulle sættes stillads op over trappen, som dermed var delvis blokeret. Det var vigtig at der ikke kom alt for mange forsinkelser. -hele arbejdet blev udført virkelig flot og hele tidsplanen holdt som aftalt -mange tak!"<br><br>Karin og Peter<br>2300 Kbh S</td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Fam. Jensen</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">07-01-2013 10:53:57</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">I forbindelse med renoveringsprojekt af vores badeværelse og bryggers, blev vi præsenteret for David og Louise, som stod for malerarbejdet hos hovedentreprenøren af projektet. Vi fik lavet et godt stykke arbejde, og som projektet skred frem, kunne vi jo godt se, hvor kedeligt resten af huset efterhåndet så ud. Så vi snakkede lidt frem og tilbage med D&amp;L, hvad der skulle til for at friske huset op og hvor stor en omkostning det ville være. Vi fandt ud af, at det faktisk ikke var så dyrt, til at starte med, men det greb lidt om sig, så det endte med, at træværk omkring vinduerne samt alle dørene på begge sider, lige så godt kunne tages med. Og hvor er vi glade for det i dag. Alle kender det med, at man skal se at få det gjort, men man får det aldrig gjort færdigt. D&amp;L hjalp os med at finde farver og foreslog, at det kunne gøres imens vi var på ferie i 14 dage, og da huset alligevel ikke var kommet på plads, ja, så kunne vi lige så godt fortsætte. Så det endte med, at vi kom hjem fra ferie til et nymalet hus, så det har vi ikke fortrudt. Der var ganske få misforståelser, men dem tog I fint, og vi fik løst de problemer der opstod undervejs, så alt i alt, er vi godt tilfredse med det færdige arbejde og de søde mennesker (D&amp;L) som udførte arbejdet.<br><br>Mvh.<br>Calle og Maj-Brit </td></tr></tbody></table>
                    <table cellpadding="0" cellspacing="0" style="width:100%; margin:5px 0 0 0;"><tbody><tr><td style="padding:5px; background-color:#F7F7F7; border-bottom:1px solid #999999;"><div style="float:left; color:#000000;"><span style="color:#333333; font-size:12px; font-weight:bold;">Jeppe Liisberg</span>&nbsp;&nbsp;(<a style="font-size:12px;" href="mailto:ukendt@ukendt.dk">ukendt@ukendt.dk</a>)</div><div style="float:right; text-align:right; color:#000000;"><span style="color:#000000; font-size:12px; font-weight:bold;">Tilføjet d.</span> <span style="color:#000000; font-size:12px;">05-11-2012 10:18:33</span></div></td></tr><tr><td style="padding:10px; border-bottom:1px solid #DADADA; color:#000000;">Maling af lejlighed.København N 16/10 - 2012<br><br>"Rigtigt flot udført, til tiden og meget god kommunikation hele vejen igennem forløbet"</td></tr></tbody></table>

                    <a class="btn_kontakt" href="kontakt.php">KONTAKT OS FOR YDERLIGERE INFORMATIONER</a>
                </div> <!--w_content-->
            </div><!--template-->
        </div><!--#container-->
        <?php require_once('footer.php'); ?> 
    </div> <!--#page--> 
</body>
</html>
